## 05_错误与异常
主要的异常类：
ZeroDevisionError
NameError
TypeError
IndexError
KeyError
ValueError
AttributeError
StopIteration

异常继承
BaseException:
    - SystemExit
    - KeyboardInterrupt
    - GeneratorExit
    - Exception


### 解决方案
#### 方案一：try except
```python
try:
    pass
except (except1,except2) as e:
    pass
except except3 as e:
    pass
else:
    pass
finally:
    pass
```

#### 方案二：with 
with语句
```python 
with open('f','r',encoding='utf-8') as fp:
    fp.read()

# 转换成上下文管理器
class Test:
    def __enter__(self):
        return self
    def __exit__(self,exc_type,exc_val,exc_tb):
        pass
```

#### 方案三：contextlib
contextlib
```python
import contextlib

@contextlib.contextmanager
def test():
	print(1)
	yield
	print(2)

with test() as t:
	print(3)
```
在yield之前的相当于在`__enter__`执行， yield之后 的则在`__exit__`执行， 使用时的`print(3)`则在yeild处执行

处理错误
```python
import contextlib.contextmanager

@contextlib.contextmanager
def ze():
	try:
		yield
	except ZeroDevisionError as e:
		print('error',e)
```

代码会走到try,然后执行，然后是捕获except 这样在需要使用的地方变成了：
```python
with ze():
    a/b
```
这样就能捕获异常

#### contextlib.closing
contextlib.closing会默认调用对象内部的closing方法：
```python
import contextlib


class Test(object):

    def close(self):
        print('close')

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

with Test() as t:
	t.run()

# 使用contextlib.closing就不需要实现__enter__, __exit__方法
with contextlib.closing(Test()) as t:
    t.run()
```

#### contextlib嵌套使用
with 可以嵌套使用，也可以转化成contextlib
```python
with open('src.txt','r') as source:
	with open('tar.txt', 'w') as target:
		src_content = source.read()
		target.write(src_content)

# 使用contextlib写法
import contextlib

with open('src.txt', 'r') as source, open('tar.txt','w') as target:
	src_content = source.read()
	target.write(src_content)
```